### PR TITLE
Update karuma.py

### PR DESCRIPTION
**Pull request by GAGOU78**

### CODE REVIEW

**Comment by GAGOU78** [comment]
sussy pull request

**Comment by hoemotion** [comment]
Bruhhh why did you remove all the notes and the automatic module installer 💀

**Comment by GAGOU78** [comment]
cuz if someone want edit the code he understand the code, he don't need to read bigga comments

**Comment by hoemotion** [comment]
Yeah but a newbie wouldn‘t understand the code without the notes

**Comment by GAGOU78** [comment]
ye but only people who understand the code gonna edit it :skull:

**Comment by hoemotion** [comment]
Yeah but people be dming me with simple things like, „is this a token grabber“, „how do i install modules“ etc. And thats why I added these things

**Comment by GAGOU78** [comment]
and the automatic module install is useless cuz there is already a requirements.txt

**Comment by hoemotion** [comment]
they dont even know how to install the things via pip install -r requirements.txt 💀

**Comment by GAGOU78** [comment]
they don't know how to install python :skull:

**Comment by hoemotion** [comment]
Fax, yesterday somebody dmed me and asked why it says that python wasnt added to the path 🤣

**Comment by GAGOU78** [comment]
if you don't merge you are gay and a horse

**Comment by GAGOU78** [comment]
and i gonna eat you

**Comment by hoemotion** [comment]
> if you don't merge you are gay and a horse

Alright you got me

**Pull request merged**
